'use strict';
angular
    .module('app.config', [])
    .config(['$mdThemingProvider', '$mdIconProvider', function ($mdThemingProvider, $mdIconProvider) {
        $mdThemingProvider
            .theme('default')
            .primaryPalette('teal')
            .accentPalette('deep-orange', {
                'default': '500'
            });

        $mdIconProvider
            .icon("menu", "./assets/svg/menu.svg", 24)
            .icon("dashboard", "./assets/svg/dashboard.svg", 24)
            .icon("prospectos", "./assets/svg/face.svg", 24)
            .icon("reportes", "./assets/svg/equalizer.svg", 24)
            .icon("configuracion", "./assets/svg/settings.svg", 24)
            .icon("perfiles", "./assets/svg/paste.svg", 24)
            .icon("enviar", "./assets/svg/send.svg", 24)
            .icon("salir", "./assets/svg/logout.svg", 24)
            .icon("buscar", "./assets/svg/search.svg", 24)
            .icon("personas", "./assets/svg/supervisor.svg", 24)
            .icon("letras", "./assets/svg/alphabetical.svg", 24)
            .icon("persona", "./assets/svg/account.svg", 24)
            .icon("dinero", "./assets/svg/money.svg", 24)
            .icon("reloj", "./assets/svg/schedule.svg", 24)
            .icon("pin_persona", "./assets/svg/pin_person.svg", 24)
            .icon("eliminar", "./assets/svg/backspace.svg", 24)
            .icon("agregar", "./assets/svg/add.svg", 24)
            .icon("lista", "./assets/svg/list.svg", 24)
            .icon("trabajo", "./assets/svg/work.svg", 24)
            .icon("checklist", "./assets/svg/assignment.svg", 24)
            .icon("siguiente", "./assets/svg/right_arrow.svg", 24)
            .icon("atras", "./assets/svg/left_arrow.svg", 24)
            .icon("etiqueta", "./assets/svg/tag.svg", 24)
            .icon("more", "./assets/svg/more.svg", 24)
            .icon("expediente", "./assets/svg/ic_folder_open.svg", 24)
            .icon("save", "./assets/svg/save.svg", 32)
            .icon("calendario", "./assets/svg/ic_today.svg", 24)
            .icon("ciudad", "./assets/svg/city.svg", 24)
            .icon("archivo", "./assets/svg/file.svg", 24)
            .icon("dobleabajo", "./assets/svg/double_down.svg", 24)
            .icon("cuenta", "./assets/svg/account_circle.svg", 24)
            .icon("tarjeta", "./assets/svg/card.svg", 24)
            .icon("canasta", "./assets/svg/basket.svg", 24)
            .icon("solicitud", "./assets/svg/ic_assignment_ind.svg", 24)
            .icon("alerta1", "./assets/svg/ic_report_problem.svg", 24)
            .icon("alerta2", "./assets/svg/ic_assignment_late.svg", 24)
            .icon("verificar", "./assets/svg/ic_assignment_in.svg", 24)
            .icon("ok1","./assets/svg/ic_assignment_in.svg", 24)
            .icon("estrella", "./assets/svg/ic_star.svg", 24)
            .icon("subir_archivo", "./assets/svg/ic_fileupload.svg", 24)
            .icon("adjunto", "./assets/svg/ic_attachment.svg", 24)
            .icon("flecha_derecha", "./assets/svg/arrow_right.svg", 24)
            .icon("flecha_izquierda", "./assets/svg/arrow_left.svg", 24)
            .icon("abajo", "./assets/svg/arrow_down.svg", 24)
            .icon("info", "./assets/svg/info.svg", 24)
            .icon("cerrar", "./assets/svg/close.svg", 24)
            .icon("conversacion", "./assets/svg/ic_chat_bubble.svg", 24)
            .icon("cancelar", "./assets/svg/cancel.svg", 24)
            .icon("agregar_persona", "./assets/svg/person_add.svg", 24)
            .icon("menu_abajo_set", "./assets/svg/menu-down_arrow.svg", 24)
            .icon("menu_arriba_set", "./assets/svg/menu-up_arrow.svg", 24)
            .icon("more-close", "./assets/svg/more-close.svg", 24)
            .icon("edicion", "./assets/svg/mode_edit.svg", 24)
            .icon("negocio", "./assets/svg/business.svg", 24)
            .icon("persona2", "./assets/svg/account_box.svg", 24)
            .icon("telefono", "./assets/svg/phone.svg", 24)
            .icon("porcentaje", "./assets/svg/percent.svg", 24)
            .icon("eliminar2", "./assets/svg/delete.svg", 24)
            .icon("pulgar_arriba", "./assets/svg/ic_thumb_up.svg", 24)
            .icon("pulgar_abajo", "./assets/svg/ic_thumb_down.svg", 24)
            .icon("pulgar_neutro", "./assets/svg/ic_thumbs_up_down.svg", 24)
            .icon("check_ok", "./assets/svg/ic_check_circle.svg", 24)
            .icon("check_error", "./assets/svg/ic_error.svg", 24)
            .icon("check_warn", "./assets/svg/ic_warning.svg", 24)
            .icon("pdf", "./assets/svg/ic_pdf.svg", 24)
            .icon("descargar1","./assets/svg/ic_vertical.svg",24)
            .icon("descargar2","./assets/svg/ic_file_download.svg",24)
            .icon("posicion","./assets/svg/map-marker.svg",24)
            .icon("agenda","./assets/svg/agenda.svg",24)
            .icon("correo","./assets/svg/correo.svg",24)
            .icon("celular","./assets/svg/celular.svg",24)
            .icon("edit","./assets/svg/edit.svg",32)
            .icon("domicilio","./assets/svg/home.svg",24)
            .icon("vistobueno","./assets/svg/vistobueno.svg",24)
            .icon("direccion","./assets/svg/direccion.svg",24)
            .icon("relacion","./assets/svg/relacion.svg",24)
            .icon("telefonoCasa","./assets/svg/telefonoCasa.svg",24)
            .icon("telefonoOficina","./assets/svg/telefonoOficina.svg",24)
            .icon("tiempo","./assets/svg/tiempo.svg",24)
            .icon("mas","./assets/svg/mas.svg",24)
            .icon("eliminar","./assets/svg/eliminar.svg",32)
            .icon("pregunta_palomita","./assets/svg/help-thick.svg",24)
            .icon("refrescar","./assets/svg/refresh.svg",24)
            .icon("filtro","./assets/svg/filter.svg",24)
            .icon("removerFiltro","./assets/svg/filter-remove.svg",24)
            .icon("ajuste","./assets/svg/build.svg",24)
            .icon("nivel","./assets/svg/nivel.svg",24)
            .icon("presentacion","./assets/svg/presentacion.svg",24)
            .icon("activos", "./assets/svg/diamond.svg", 24)
            .icon("clear", "./assets/svg/ic_clear_white_48px.svg", 48)    }])
    .config(['blockUIConfig', function(blockUIConfig) {

        blockUIConfig.autoBlock = false;

        blockUIConfig.message = '';

        blockUIConfig.delay = 0;

    }]
)
;
